// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:planting_calendar_2/models/crop.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CropAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CropAdapter());
  }
}
